server:
  port: 8020


spring:
  datasource:
    name: orderingsystem
    url: jdbc:mysql://localhost:3306/orderingsystem?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 137711hb
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: menu
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: org.huang.entity